version: "3"

services:
  postgres:
    build:
      context: .
      dockerfile: ./docker/pg-Dockerfile
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  subquery-node-kaia:
    image: subquerynetwork/subql-node-ethereum:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=app/project-kaia.yaml
      - --multi-chain
      - --db-schema=multi-messages
      - --disable-historical
      - --block-confirmations=1
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://subquery-node-project-kaia:3000/ready
      interval: 3s
      timeout: 5s
      retries: 10

  subquery-node-finschia:
    image: subquerynetwork/subql-node-cosmos:latest
    depends_on:
      "postgres":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - -f=app/project-finschia.yaml
      - --multi-chain
      - --db-schema=multi-messages
      - --disable-historical
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://subquery-node-project-finschia:3000/ready
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: subquerynetwork/subql-query:latest
    ports:
      - 3000:3000
    depends_on:
      "postgres":
        condition: service_healthy
    restart: unless-stopped
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=multi-messages
      - --playground